# Generated by Django 4.0.2 on 2022-03-05 14:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0002_rename_fees_in_workld_movie_fees_in_world_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='get_categories', to='movie.category', verbose_name='Категория'),
        ),
    ]
