# Generated by Django 4.0.2 on 2022-03-14 12:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0003_alter_movie_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='yaer',
            new_name='year',
        ),
    ]
