# Generated by Django 4.0.2 on 2022-03-14 13:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0004_rename_yaer_movie_year'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='geners',
            new_name='genres',
        ),
    ]
