# Generated by Django 4.0.2 on 2022-03-18 16:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0005_rename_geners_movie_genres'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ratingstar',
            options={'ordering': ['-value'], 'verbose_name': 'Звезда рейтинга', 'verbose_name_plural': 'Звезды рейтинга'},
        ),
    ]
