# Generated by Django 4.0.2 on 2022-03-23 12:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0007_category_movie'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category_movie',
            options={'verbose_name': 'Категория', 'verbose_name_plural': 'Категории movies '},
        ),
    ]
