# Generated by Django 4.0.2 on 2022-03-27 15:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0008_alter_category_movie_options'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Category_movie',
        ),
    ]
