# Generated by Django 4.0.2 on 2022-03-28 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0009_delete_category_movie'),
    ]

    operations = [
        migrations.AddField(
            model_name='actor',
            name='url',
            field=models.SlugField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
