# Generated by Django 4.0.2 on 2022-04-01 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0012_item'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='genres',
            field=models.ManyToManyField(related_name='get_genres', to='movie.Genre', verbose_name='жанры'),
        ),
    ]
