# Generated by Django 4.0.2 on 2022-04-01 11:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0014_alter_movie_category_alter_movie_genres_series'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='category',
        ),
        migrations.RemoveField(
            model_name='series',
            name='category',
        ),
        migrations.RemoveField(
            model_name='series',
            name='genres',
        ),
        migrations.AddField(
            model_name='movie',
            name='series',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='get_series', to='movie.series', verbose_name='series'),
        ),
        migrations.AddField(
            model_name='series',
            name='description',
            field=models.TextField(default=1, verbose_name='Описание'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='series',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='series',
            name='url',
            field=models.SlugField(max_length=255),
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
