# Generated by Django 4.0.2 on 2022-04-01 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0015_remove_movie_category_remove_series_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='series',
            name='genres',
            field=models.ManyToManyField(related_name='get_series_genres', to='movie.Genre', verbose_name='жанры'),
        ),
    ]
