# Generated by Django 4.0.2 on 2022-04-09 05:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0019_alter_movie_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='series',
        ),
        migrations.RemoveField(
            model_name='series',
            name='description',
        ),
        migrations.AddField(
            model_name='series',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='get_series_categories', to='movie.category', verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='get_movies_categories', to='movie.category', verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='series',
            name='title',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='series',
            name='url',
            field=models.SlugField(max_length=255, unique=True),
        ),
    ]
