# Generated by Django 4.0.2 on 2022-04-09 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0021_remove_movie_category_remove_series_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Genre_series',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('descrption', models.TextField()),
                ('url', models.SlugField(max_length=255, unique=True)),
            ],
            options={
                'verbose_name': 'Series genre',
                'verbose_name_plural': 'Series genres',
            },
        ),
        migrations.RenameModel(
            old_name='Genre',
            new_name='Genre_movie',
        ),
        migrations.AlterModelOptions(
            name='genre_movie',
            options={'verbose_name': 'Movie genre', 'verbose_name_plural': 'Movie genres'},
        ),
        migrations.AlterField(
            model_name='series',
            name='genres',
            field=models.ManyToManyField(related_name='get_series_genres', to='movie.Genre_series', verbose_name='жанры'),
        ),
    ]
