# Generated by Django 4.0.2 on 2022-04-09 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0022_genre_series_rename_genre_genre_movie_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Genre_anime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('descrption', models.TextField()),
                ('url', models.SlugField(max_length=255, unique=True)),
            ],
            options={
                'verbose_name': 'Anime genre',
                'verbose_name_plural': 'Anime genres',
            },
        ),
        migrations.CreateModel(
            name='Genre_cartoon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('descrption', models.TextField()),
                ('url', models.SlugField(max_length=255, unique=True)),
            ],
            options={
                'verbose_name': 'Cartoon genre',
                'verbose_name_plural': 'Cartoon genres',
            },
        ),
        migrations.CreateModel(
            name='Cartoon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('url', models.SlugField(max_length=255, unique=True)),
                ('genres', models.ManyToManyField(related_name='get_cartoon_genres', to='movie.Genre_series', verbose_name='жанры')),
            ],
        ),
        migrations.CreateModel(
            name='Anime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('url', models.SlugField(max_length=255, unique=True)),
                ('genres', models.ManyToManyField(related_name='get_anime_genres', to='movie.Genre_series', verbose_name='жанры')),
            ],
        ),
    ]
