# Generated by Django 4.0.2 on 2022-04-09 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0023_genre_anime_genre_cartoon_cartoon_anime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anime',
            name='genres',
            field=models.ManyToManyField(related_name='get_anime_genres', to='movie.Genre_anime', verbose_name='жанры'),
        ),
        migrations.AlterField(
            model_name='cartoon',
            name='genres',
            field=models.ManyToManyField(related_name='get_cartoon_genres', to='movie.Genre_cartoon', verbose_name='жанры'),
        ),
    ]
