# Generated by Django 4.0.2 on 2022-04-17 10:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0025_alldata'),
    ]

    operations = [
        migrations.CreateModel(
            name='MovieVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caption', models.CharField(max_length=255)),
                ('video', models.FileField(upload_to='video/%y')),
            ],
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caption', models.CharField(max_length=200)),
                ('video', models.FileField(upload_to='video/%y')),
            ],
        ),
        migrations.AddField(
            model_name='movie',
            name='videos',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='movie_videos', to='movie.movievideo'),
            preserve_default=False,
        ),
    ]
