# Generated by Django 4.0.2 on 2022-04-17 10:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0026_movievideo_video_movie_videos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='videos',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movie_videos', to='movie.movievideo'),
        ),
    ]
