# Generated by Django 4.0.2 on 2022-04-17 10:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0027_alter_movie_videos'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Video',
        ),
    ]
