# Generated by Django 4.0.2 on 2022-05-07 09:47

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0029_alter_movie_videos'),
    ]

    operations = [
        migrations.CreateModel(
            name='SeriesVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caption', models.CharField(max_length=255)),
                ('video', models.FileField(upload_to='video/%y')),
            ],
        ),
        migrations.AddField(
            model_name='series',
            name='budget',
            field=models.PositiveIntegerField(default=0, help_text='указать сумму в долларах', verbose_name='Бюджет'),
        ),
        migrations.AddField(
            model_name='series',
            name='country',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='series',
            name='description',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='series',
            name='draft',
            field=models.BooleanField(default=False, verbose_name='Черновик'),
        ),
        migrations.AddField(
            model_name='series',
            name='fees_in_usa',
            field=models.PositiveIntegerField(default=0, help_text='указать сумму в долларах', verbose_name='Сборы в США'),
        ),
        migrations.AddField(
            model_name='series',
            name='fees_in_world',
            field=models.PositiveIntegerField(default=0, help_text='указать сумму в долларах', verbose_name='сборы в мире'),
        ),
        migrations.AddField(
            model_name='series',
            name='poster',
            field=models.ImageField(default=1, upload_to='movies/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='series',
            name='tagline',
            field=models.CharField(default=1, max_length=255, verbose_name='Слоган'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='series',
            name='world_premier',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='series',
            name='year',
            field=models.PositiveIntegerField(default=2022, verbose_name='дата выхода'),
        ),
        migrations.AddField(
            model_name='series',
            name='videos',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='movie_videos', to='movie.seriesvideo'),
            preserve_default=False,
        ),
    ]
