# Generated by Django 4.0.2 on 2022-05-07 09:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0030_seriesvideo_series_budget_series_country_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movievideo',
            name='caption',
        ),
        migrations.RemoveField(
            model_name='seriesvideo',
            name='caption',
        ),
    ]
