# Generated by Django 4.0.2 on 2022-05-07 10:04

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0031_remove_movievideo_caption_remove_seriesvideo_caption'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnimeVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video', models.FileField(upload_to='video/%y')),
            ],
        ),
        migrations.CreateModel(
            name='CartoonVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video', models.FileField(upload_to='video/%y')),
            ],
        ),
        migrations.AddField(
            model_name='anime',
            name='budget',
            field=models.PositiveIntegerField(default=0, help_text='указать сумму в долларах', verbose_name='Бюджет'),
        ),
        migrations.AddField(
            model_name='anime',
            name='country',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='anime',
            name='description',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='anime',
            name='draft',
            field=models.BooleanField(default=False, verbose_name='Черновик'),
        ),
        migrations.AddField(
            model_name='anime',
            name='fees_in_usa',
            field=models.PositiveIntegerField(default=0, help_text='указать сумму в долларах', verbose_name='Сборы в США'),
        ),
        migrations.AddField(
            model_name='anime',
            name='fees_in_world',
            field=models.PositiveIntegerField(default=0, help_text='указать сумму в долларах', verbose_name='сборы в мире'),
        ),
        migrations.AddField(
            model_name='anime',
            name='poster',
            field=models.ImageField(default=1, upload_to='movies/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='anime',
            name='tagline',
            field=models.CharField(default=1, max_length=255, verbose_name='Слоган'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='anime',
            name='world_premier',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='anime',
            name='year',
            field=models.PositiveIntegerField(default=2022, verbose_name='дата выхода'),
        ),
        migrations.AddField(
            model_name='cartoon',
            name='budget',
            field=models.PositiveIntegerField(default=0, help_text='указать сумму в долларах', verbose_name='Бюджет'),
        ),
        migrations.AddField(
            model_name='cartoon',
            name='country',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cartoon',
            name='description',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cartoon',
            name='draft',
            field=models.BooleanField(default=False, verbose_name='Черновик'),
        ),
        migrations.AddField(
            model_name='cartoon',
            name='fees_in_usa',
            field=models.PositiveIntegerField(default=0, help_text='указать сумму в долларах', verbose_name='Сборы в США'),
        ),
        migrations.AddField(
            model_name='cartoon',
            name='fees_in_world',
            field=models.PositiveIntegerField(default=0, help_text='указать сумму в долларах', verbose_name='сборы в мире'),
        ),
        migrations.AddField(
            model_name='cartoon',
            name='poster',
            field=models.ImageField(default=1, upload_to='movies/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cartoon',
            name='tagline',
            field=models.CharField(default=1, max_length=255, verbose_name='Слоган'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cartoon',
            name='world_premier',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='cartoon',
            name='year',
            field=models.PositiveIntegerField(default=2022, verbose_name='дата выхода'),
        ),
        migrations.AlterField(
            model_name='series',
            name='videos',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='series_videos', to='movie.seriesvideo'),
        ),
        migrations.AddField(
            model_name='anime',
            name='videos',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='movie_videos', to='movie.animevideo'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cartoon',
            name='videos',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='movie_videos', to='movie.cartoonvideo'),
            preserve_default=False,
        ),
    ]
