# Generated by Django 4.0.2 on 2022-05-07 10:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0032_animevideo_cartoonvideo_anime_budget_anime_country_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='series',
            name='videos',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='series_videos', to='movie.seriesvideo'),
        ),
    ]
