# Generated by Django 4.0.2 on 2022-05-11 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0036_alter_review_options_remove_review_series_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='review',
            options={'verbose_name': 'Отзыв', 'verbose_name_plural': 'Отзывы'},
        ),
        migrations.AlterModelOptions(
            name='seriesreview',
            options={},
        ),
        migrations.AlterField(
            model_name='seriesvideo',
            name='video',
            field=models.FileField(upload_to='series/video/%y'),
        ),
    ]
