# Generated by Django 4.0.2 on 2022-05-11 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0037_alter_review_options_alter_seriesreview_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartoonvideo',
            name='video',
            field=models.FileField(upload_to='cartoon/video/%y'),
        ),
    ]
