# Generated by Django 4.0.2 on 2022-05-11 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0038_alter_cartoonvideo_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movievideo',
            name='video',
            field=models.FileField(upload_to='movies/video/%y'),
        ),
    ]
