# Generated by Django 4.0.2 on 2022-05-11 07:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0039_alter_movievideo_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='series',
            name='videos',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='series_videos', to='movie.seriesvideo'),
        ),
    ]
