# Generated by Django 4.0.2 on 2022-05-15 16:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0040_alter_series_videos'),
    ]

    operations = [
        migrations.CreateModel(
            name='CartoonReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('name', models.CharField(max_length=255)),
                ('text', models.TextField(max_length=5000, verbose_name='Отзыв')),
                ('cartoon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews_set_series', to='movie.cartoon', verbose_name='сериалы')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='comments_cartoon_comment', to='movie.cartoonreview', verbose_name='Подотзыв')),
            ],
        ),
        migrations.CreateModel(
            name='AnimeReiview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('name', models.CharField(max_length=255)),
                ('text', models.TextField(max_length=5000, verbose_name='Отзыв')),
                ('anime', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews_set_series', to='movie.anime', verbose_name='сериалы')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='comments_anime_comment', to='movie.animereiview', verbose_name='Подотзыв')),
            ],
        ),
    ]
